### ISSUE TITLE
How to run this extention?

### ISSUE THREAD

**Issue by elszon** [zoellner/openapi-preview#12]
Hi, 

I'm trying to run OpenAPI preview but only what I get is white window. I don't have any popup window or any error reported. Same happen on MacOS and on Ubuntu 22.04.

Is there any external tool which need to be installed on local machine.

File which I want to preview: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/api-with-examples.yaml

**Comment by zoellner** [comment]
Thank you for reporting this. 
This is a bug in the latest version. It works fine during development, but not in the published version due to some missing files. VS Code doesn't have a good way to include additional files, but I'm testing a workaround and should have a working version published soon.

**Comment by zoellner** [comment]
Can you test it with v2.1.5 and let me know if it works for you?

**Comment by elszon** [comment]
It's better but still no good preview.

![image](https://github.com/zoellner/openapi-preview/assets/2971495/e60b7e26-66af-4d53-94ef-bad754f80ff8)

**Comment by zoellner** [comment]
glad you could confirm that this bug is fixed.

The issue you are seeing now seems to be because of an invalid spec. When you check this one: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/uspto.yaml it should work fine. 

This extension is using https://stoplight.io/open-source/elements to render the preview, so the issue with this particular spec should be reported there

**Comment by elszon** [comment]
Many thanks.
